version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'emp_consulting'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3308:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata: